version: '3.8'
services:
  service_node:
    image: node:18.18.0
    ports:
      - 3000:3000
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
  service_postgres:
    image: postgres:latest
    container_name: container_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb01
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      - ./postgres_service/initdb.d:/docker-entrypoint-initdb.d
  service_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: container_pgadmin
    ports:
      - 8080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - service_postgres
volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga